export const MARK_AS_READ = 'MARK_AS_READ';
export const SET_TYPE_FILTER = 'SET_TYPE_FILTER';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const FILTERS = { DEFAULT: 'DEFAULT', URGENT: 'URGENT' };

export const NotificationTypeFilters = {
  DEFAULT: 'DEFAULT',
  URGENT: 'URGENT'
}